# permissions for end users to edit backupmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-db-compliance-operator
    app.kubernetes.io/managed-by: kustomize
  name: backupmonitor-editor-role
rules:
- apiGroups:
  - backup.my.domain
  resources:
  - backupmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.my.domain
  resources:
  - backupmonitors/status
  verbs:
  - get
