---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.example.com
  - backup.my.domain
  resources:
  - backupmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.example.com
  - backup.my.domain
  resources:
  - backupmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - backup.example.com
  - backup.my.domain
  resources:
  - backupmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - get
  - list
  - watch
