//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupMonitor) DeepCopyInto(out *BackupMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupMonitor.
func (in *BackupMonitor) DeepCopy() *BackupMonitor {
	if in == nil {
		return nil
	}
	out := new(BackupMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupMonitorList) DeepCopyInto(out *BackupMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupMonitorList.
func (in *BackupMonitorList) DeepCopy() *BackupMonitorList {
	if in == nil {
		return nil
	}
	out := new(BackupMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupMonitorSpec) DeepCopyInto(out *BackupMonitorSpec) {
	*out = *in
	if in.EnabledNamespaces != nil {
		in, out := &in.EnabledNamespaces, &out.EnabledNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupMonitorSpec.
func (in *BackupMonitorSpec) DeepCopy() *BackupMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(BackupMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupMonitorStatus) DeepCopyInto(out *BackupMonitorStatus) {
	*out = *in
	if in.ProcessedDeployments != nil {
		in, out := &in.ProcessedDeployments, &out.ProcessedDeployments
		*out = make([]ProcessedDeployment, len(*in))
		copy(*out, *in)
	}
	in.LastResyncTime.DeepCopyInto(&out.LastResyncTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupMonitorStatus.
func (in *BackupMonitorStatus) DeepCopy() *BackupMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(BackupMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcessedDeployment) DeepCopyInto(out *ProcessedDeployment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcessedDeployment.
func (in *ProcessedDeployment) DeepCopy() *ProcessedDeployment {
	if in == nil {
		return nil
	}
	out := new(ProcessedDeployment)
	in.DeepCopyInto(out)
	return out
}
